### ISSUE TITLE
Aspire 9 support

### ISSUE THREAD

**Issue by aaronpowell** [CommunityToolkit/Aspire#56]
Aspire 9 is [in development](https://github.com/dotnet/aspire/milestone/23) with the intention of shipping in November.

We should begin testing the integration with Aspire 9 so that when it is released we are ready to ship packages that support it.

```[tasklist]
### Tasks
- [x] Create a branch for Aspire 9 testing
- [x] Upgrade the NuGet package dependencies for Aspire to 9.x release
- [x] Update our major version number to be 9
- [x] Remove workload install on GitHub Actions workflows
- [x] Fix any bugs that come up!
- [ ] https://github.com/CommunityToolkit/Aspire/issues/223
```
